### ISSUE TITLE
Node Page doesn't show new nodes that just showed up

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#279] opened 2020-05-02 11:30 UTC
If I have Node Page open, and there is a new node that started sending telemetry, Node Page won't have it in the list.
Note, that it will change the total counter of validator/non-validator nodes for it.

Steps to reproduce:
----
1. Open explorer page
2. Start a new node 
3. Observe that counters changed but node is not in the list

PS. refreshing page shows it.

**Comment by frol** [comment] 2020-05-02 12:49
It is a duplicate of #268

**Closed by frol** 2020-05-02 12:49 UTC
