### ISSUE TITLE
Some failed transaction is shown as succeeded

### ISSUE THREAD

**Issue by ailisp** [near/near-explorer#475] opened 2020-11-11 18:23 UTC
For example this one:
https://explorer.near.org/transactions/AJNQRJX7yri7sc4y7ypbCC1s9PDS5zrc7ur7mFTxS8Kk

It has a success receipt, but the final result is a failure

**Comment by frol** [comment] 2020-11-11 18:41
Duplicate of https://github.com/near/near-explorer/issues/358

**Closed by frol** 2020-11-11 18:41 UTC
