### ISSUE TITLE
Show Internal Actions: transfers, add key, delete key, ... as "Top Level" in Actions/Transactions List

### ISSUE THREAD

**Issue by mattlockyer** [near/near-explorer#337] opened 2020-06-25 16:57 UTC
## Story

As a casual user who doesn't know much, I want to see internal contract actions so I can understand how contracts like Multisig that transfer Near are changing my balance.

Currently when a multisig request is confirmed and successful it shows up like this:
![image](https://user-images.githubusercontent.com/321340/85762305-74f2b900-b6c8-11ea-9008-91d0ab31fe0a.png)

This doesn't tell the user anything about what the multisig request actually did, e.g. it may have transferred funds, but they don't know to who and how much.

## Acceptance Criteria

- [ ] Explorer shows internal Near transfers broken out in list of transactions, like it does for AddKey
- [ ] Explorer shows **other** internal contract actions such as AddKey, DeleteKey
- [ ] Mobile ok
- [ ] Tested

## Currently Looks Like (with Multisig Contract Account)
![image](https://user-images.githubusercontent.com/321340/85761338-825b7380-b6c7-11ea-94e5-6bb203788a65.png)
![image](https://user-images.githubusercontent.com/321340/85761373-8b4c4500-b6c7-11ea-9742-3f8ab3986c58.png)

## Need it to Look Like
- show internal contract transfers like this so they are more prominent
Include:
- receiver accountId
- amount
![image](https://user-images.githubusercontent.com/321340/85763605-addf5d80-b6c9-11ea-8199-e739288ca3eb.png)
- Also show other internal actions like this:
![image](https://user-images.githubusercontent.com/321340/85763703-c6e80e80-b6c9-11ea-83f6-3b24fbf88fa7.png)

## NOTES
- feedback appreciated

**Comment by icerove** [comment] 2020-06-25 23:13
@kcole16 need some sample cases here and needs design. I do not see other case to include the requests like transfer in the argument. What format is used here?

**Comment by mattlockyer** [comment] 2020-06-26 03:57
@icerove is there no record of what a contract executes on chain? There are several protocol level methods a contract promise may execute:
- create_account
- transfer
- add_access_key
- delete_key
...

I performed some of these using the multisig contract with this account: https://explorer.testnet.near.org/accounts/dev-1593100552143

But all I see are the multisig contract method calls. The "internal" transactions of the contract are not shown like in these examples:
![image](https://user-images.githubusercontent.com/321340/85818811-87034480-b726-11ea-8db6-1d221706911a.png)

**Comment by frol** [comment] 2020-06-26 06:19
“Internal transactions” are receipts, and thus, this issue is a duplicate of #218 (the current backend does not track receipts, but we are going to address this with Network Indexer #236 in a course of the next few weeks)

**Closed by frol** 2020-06-26 06:19 UTC
Labels: Needs Design, enhancement

**Comment by mattlockyer** [comment] 2020-06-26 15:31
@frol thanks for the clarity. Due to the nomenclature (still learning) e.g. receipts, it was hard to determine that this issue was being tracked.

**Comment by kcole16** [comment] 2020-06-26 15:35
@mattlockyer My fault on this! I'll add your context to the receipts issue (and also think about how we can communicate to Ethereum users that receipts are similar to internal transactions)
