### ISSUE TITLE
wrong attached gas

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-explorer#1092] opened 2022-09-01 13:21 UTC
This is a transaction with wrong attached gas, attached **30 T**, but used **174 T**
https://explorer.testnet.near.org/transactions/2Pn1eCirSRvqa31cYa6xhj97aygqsQPVXBzRHUMgH4xP
<img width="1129" alt="1" src="https://user-images.githubusercontent.com/95295094/187923977-7922c846-0fd1-42e2-89eb-499524c5d1b2.png">

**Comment by frol** [comment] 2022-09-03 04:07
It is a duplicate of #232. We most probably need to remove the attached gas cell completely as it is semantically incorrect here, and add attached gas and attached tokens to the function call action details. Explorer development is currently on hold, so it is not going to be addressed soon unless someone submits a PR.

**Closed** 2022-11-01 07:45 UTC
